name: prj
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 1.13
  - torchvision
  - pytorch-cuda=11.7
  - pip
  - pip:
    - timm
    - diffusers
    - lmdb
    - accelerate
    - taming-transformers
    - einops
    - matplotlib
    - pytorch_lightning
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
